logging:
  receivers:
    my-app-receiver:
      type: files
      include_paths:
        - /var/log/webapp/myapp.log
      record_log_file_path: true
  processors:
    my-app-processor:
      type: parse_json
      time_key: timeMillis
      time_format:  "%f"
    move_severity:
      type: modify_fields
      fields:
        severity:
          move_from: jsonPayload.level
          map_values:
            WARN: WARNING
  service:
    pipelines:
      default_pipeline:
        receivers: [my-app-receiver]
        processors: [my-app-processor, move_severity]