logging:
  receivers:
    my-app-receiver:
      type: files
      include_paths:
        - /var/log/webapp/myapp.log
      record_log_file_path: true
  processors:
    my-app-processor:
      type: parse_regex
      field: message
      regex: '^{.*"epochSecond" : (?<timestamp>\d+).*"thread" : "(?<thread>[^"]+)".*"level" : "(?<severity>[^"]+)".*"loggerName" : "(?<logger>[^"]+)".*"message" : "(?<message>[^"]+)"'
      time_key: time
      time_format: "%Y-%m-%d %H:%M:%S.%L"
    move_severity:
      type: modify_fields
      fields:
        severity:
          move_from: jsonPayload.severity
    parse_java_multiline:
      type: parse_multiline
      match_any:
        - type: language_exceptions
          language: java
  service:
    pipelines:
      default_pipeline:
        receivers: [my-app-receiver]
        processors: [my-app-processor, move_severity, parse_java_multiline]