logging:
  receivers:
    my-app-receiver:
      type: files
      include_paths:
        - /var/log/webapp/myapp.log
      record_log_file_path: true
  processors:
    my-app-processor:
      type: parse_json
      time_key: instant.epochSecond
      time_format: "%s"
    move_severity:
      type: modify_fields
      fields:
        severity:
          move_from: jsonPayload.level
    parse_java_multiline:
      type: parse_multiline
      match_any:
        - type: language_exceptions
          language: java
  service:
    pipelines:
      default_pipeline:
        receivers: [my-app-receiver]
        processors: [my-app-processor, move_severity, parse_java_multiline]