name: Build artifact and Create image
on:
  pull_request:
    branches:
      - 'main'


jobs:
  Build-and-deliver:
    if: github.event.pull_request.head.repo.fork == true
    runs-on: ubuntu-latest

    steps:
      - name: Set up PostgreSQL
        run: |
          sudo apt-get update

          # Install PostgreSQL
          sudo apt-get install -y postgresql postgresql-contrib

          sudo systemctl start postgresql
          sudo systemctl enable postgresql

          sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'root';"
          sudo -u postgres psql -c "CREATE DATABASE webapp WITH OWNER = postgres;"

          sudo systemctl restart postgresql

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '19'

      - name: Setup Maven
        run: chmod +x mvnw && ./mvnw clean package

      - name: Run Integration Tests
        run: mvn verify -DskipTests=false -B

      - name: Zip Project
        run: |
          zip -r webapp.zip ./target ./startup-scripts
          pwd
          ls -l

      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'

      - name: Set up Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: 'latest'

      - name: Run `packer init`
        id: init
        run: packer init ./machine-image/centos.pkr.hcl

      - name: Run `packer validate`
        id: validate
        run: packer validate ./machine-image/centos.pkr.hcl

      - name: Run packer script
        run: packer build ./machine-image/centos.pkr.hcl
