name: Github Actions
on:
  pull_request:
    branches:
      - 'main'

jobs:
  Springboot-Setup:
    if: github.event.pull_request.head.repo.fork
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: "postgres"
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "root"
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '19'

      - name: Build Spring Boot application
        run: chmod +x mvnw && ./mvnw clean install

      - name: Run Spring Boot application
        run: ./mvnw spring-boot:run


      - name: Stop Spring Boot application
        run: |
          pkill -f '.*spring-boot:run.*'