name: Integration tests
on:
  pull_request:
    branches:
      - 'main'

jobs:
  Integration-test-check:
    if: github.event.pull_request.head.repo.fork
    runs-on: ubuntu-latest

    steps:
      - name: Set up PostgreSQL
        run: |
          sudo apt-get update
          
          # Install PostgreSQL
          sudo apt-get install -y postgresql postgresql-contrib
          
          sudo systemctl start postgresql
          sudo systemctl enable postgresql
          
          sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'root';"
          sudo -u postgres psql -c "CREATE DATABASE webapp WITH OWNER = postgres;"

          sudo systemctl restart postgresql


      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'

      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '19'

      - name: Setup Maven
        run: chmod +x mvnw && ./mvnw clean package

      - name: Build and Run Integration Tests
        run: mvn verify -DskipTests=false -B