name: Integration tests
on:
  pull_request:
    branches:
      - 'main'

jobs:
  Integration-test-check:
    if: github.event.pull_request.head.repo.fork
    runs-on: ubuntu-latest

    steps:
      - name: Set up PostgreSQL
        run: |
          sudo apt-get update
          
          # Install PostgreSQL
          sudo apt-get install -y postgresql postgresql-contrib
          
          # Initialize the PostgreSQL database and start the service
          sudo systemctl enable postgresql

          echo $pwd
          cd /home/runner/work/webapp/webapp
          echo $pwd

          # Create a PostgreSQL user and database for your Spring Boot project
          sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'root';"
          sudo -u postgres psql -c "CREATE DATABASE webapp WITH OWNER = postgres;"
          
          # Grant necessary privileges to the user
          sudo -u postgres psql -c "ALTER USER postgres WITH SUPERUSER;"
          echo "changeeee"
          # Restart PostgreSQL service
          sudo sed -i 's/peer/scram-sha-256/' /etc/postgresql/*/main/pg_ident.conf
          sudo systemctl restart postgresql


      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '19'

      - name: Setup Maven
        run: chmod +x mvnw && ./mvnw clean package

      - name: Build and Run Integration Tests
        run: mvn verify -DskipTests=false -B