name: Integration tests
on:
  pull_request:
    branches:
      - 'main'

jobs:
  Integration-test-check:
    if: github.event.pull_request.head.repo.fork
    runs-on: ubuntu-latest

    steps:
      - name: Set up PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install postgresql postgresql-contrib
          sudo service postgresql start
          sudo sed -i 's/peer/trust/' /etc/postgresql/*/main/pg_hba.conf
          sudo service postgresql restart
          psql -U postgres -c "CREATE DATABASE webapp;"
          psql -U postgres -c "CREATE USER postgres WITH PASSWORD 'root';"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '19'

      - name: Setup Maven
        run: chmod +x mvnw && ./mvnw clean package

      - name: Build and Run Integration Tests
        run: mvn verify -DskipTests=false -B