name: Integration tests
on:
  pull_request:
    branches:
      - 'main'

jobs:
  Integration-test-check:
    if: github.event.pull_request.head.repo.fork
    runs-on: ubuntu-latest

    steps:
      - name: Set up Packer
        uses: hashicorp/setup-packer@v1
        id: setup
        with:
          version: '1.8.6'

      - name: Run `packer init`
        id: init
        run: packer init ./machine-image/centos.pkr.hcl

      - name: Run `packer validate`
        id: validate
        run: packer validate ./machine-image/centos.pkr.hcl

      - name: Run `packer fmt`
        id: format
        run: packer fmt ./machine-image/centos.pkr.hcl -check=true