name: Validate Packer
on:
  pull_request:
    branches:
      - 'main'

jobs:
  Packer-validation:
    if: github.event.pull_request.head.repo.fork
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: 'latest'

      - name: Run `packer init`
        id: init
        run: packer init ./machine-image/centos.pkr.hcl

      - name: Run `packer validate`
        id: validate
        run: |
          zip -r webapp.zip ./startup-scripts
          packer validate ./machine-image/centos.pkr.hcl

      - name: Run `packer fmt`
        id: format
        run: packer fmt ./machine-image/centos.pkr.hcl -check=true